version: '3.9'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=url_shortener
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redisdata:/var/lib/redis/data

  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - REDIS_HOST=${REDIS_HOST_DOCKER}
      
volumes:
  pgdata:
  redisdata:
